---
editor_options: 
  markdown: 
    wrap: sentence
---

\newpage

# What's Data Science and How Do I Do It?


## What's R?

`R` is a programming language developed by statisticians in the early 90s to calculate and visualize statistical results.
A lot has happened since then, and by now, `R` is one of the most widely used programming languages in Data Science.
You don't have to compile your 'R' code, but you can use it interactively and dynamically.
Such an approach makes it possible to quickly gain basic knowledge about existing data and display it graphically.

`R` offers much more than just programming.
The language provides a complete ecosystem for solving statistical problems.
A large number of packages and interfaces are available, which you can use to expand the basic functionality of the programing language to, say, create a COVID-Tracker application.

### RStudio Cloud

Before you can use `R`, you usually have to install some separate programs locally on your computer.
Typically, you first install a ["raw" version](https://rstudio-education.github.io/hopr/starting.html) of `R`.
In theory, you can then start programming.
However, it is challenging to carry out an entire project with a "raw" version of R.
That's why there is [RStudio](https://www.rstudio.com/products/rstudio/download/), a free Integrated Development Environment (IDE) for `R`.

Such IDE includes many essential features that simplify programming with `R`.
Among other things, an auto-completion of your code, a friendly user interface, and many expansion options.
Think of R as your car's engine.
And think of RStudio as your car's dashboard that shows fancy metrics, has a radio and allows you to adjust air-conditioning!

Experience has shown that installing `R` and RStudio locally on your computer takes some effort.
Fortunately, RStudio also has a cloud solution that eliminates these steps: [RStudio Cloud](https://rstudio.cloud).
You can edit your project in the same IDE in the browser without any prior installations on your computer.
You can also easily switch your project from a private to a public project and give your team an insight into your code via a link or by giving them access to the workspace directly.
In this way, you can easily exchange ideas with your team.

We will introduce RStudio Cloud and unlock access to our workspace on our first Coding Meetup.
Until then, focus on learning the "hard skills" of programming with the courses on DataCamp.
That brings us to your curriculum in the next section!

### Curriculum and DataCamp courses

The following list shows the required DataCamp courses for the Data Science with `R` Track at TechAcademy.
As a beginner, please stick to the courses of the "beginner" program.
Ambitious beginners can, of course, take the advanced courses afterward.
However, it would be best if you worked through the courses in the order we listed them.

The same applies to the advanced courses.
Here, too, you should finish the specified courses in the given order.
Since it can, of course, happen that you have already mastered the topics of an advanced course, you can replace some courses.
If you are convinced that the course does not add value to you, feel free to replace it with one of the courses in the "Exchange Pool" (see list below).
However, you should not pursue an exchange course until you finish all chapters from the advanced course: "Intermediate R."

To receive the certificate, both beginners and advanced learners must complete at least two-thirds of the curriculum (6/9 courses).
For the beginners, this means until -- and including -- the course [Cleaning Data in R (4h)](https://www.datacamp.com/courses/cleaning-data-in-r) and for the advanced until --and including -- [Modeling with Data in the Tidyverse (4h)](https://app.datacamp.com/learn/courses/modeling-with-data-in-the-tidyverse).
In addition, you should complete at least *two-thirds* of the project tasks.
After completing the curriculum and the project's (minimal) requirements, you will receive your TechAcademy certificate!

::: {.tips .r data-latex="r"}
**R Fundamentals (Beginner Track)**

1.  [Introduction to R (4h)](https://www.datacamp.com/courses/free-introduction-to-r)
2.  [Intermediate R (6h)](https://www.datacamp.com/courses/intermediate-r)
3.  [Data Manipulation with dplyr (4h)](https://www.datacamp.com/courses/data-manipulation-with-dplyr-in-r)
4.  [Introduction to Data Visualization with ggplot2 (4h)](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
5.  [Introduction to Importing Data in R (3h)](https://www.datacamp.com/courses/importing-data-in-r-part-1)
6.  [Cleaning Data in R (4h)](https://www.datacamp.com/courses/cleaning-data-in-r)
7.  [Working with Dates and Times in R (4h)](https://app.datacamp.com/learn/courses/working-with-dates-and-times-in-r)
8.  [Exploratory Data Analysis in R (4h)](https://www.datacamp.com/courses/exploratory-data-analysis)
9.  [Introduction to Statistics in R (4h)](https://app.datacamp.com/learn/courses/introduction-to-statistics-in-r)

**Data Science in R (Advanced Track)**

1.  [Intermediate R (6h)](https://www.datacamp.com/courses/intermediate-r)
2.  [Cleaning Data in R (4h)](https://www.datacamp.com/courses/cleaning-data-in-r)
3.  [Intermediate Data Visualization with ggplot2 (4h)](https://www.datacamp.com/courses/data-visualization-with-ggplot2-2)
4.  [Exploratory Data Analysis in R (4h)](https://www.datacamp.com/courses/exploratory-data-analysis)
5.  [Intermediate Regression in R (4h)](https://app.datacamp.com/learn/courses/intermediate-regression-in-r)
6.  [Modeling with Data in the Tidyverse (4h)](https://app.datacamp.com/learn/courses/modeling-with-data-in-the-tidyverse)
7.  [Time Series Analysis in R (4h)](https://app.datacamp.com/learn/courses/time-series-analysis-in-r)
8.  [Supervised Learning in R: Classification (4h)](https://www.datacamp.com/courses/supervised-learning-in-r-classification)
9.  [Machine Learning with caret in R (4h)](https://www.datacamp.com/courses/machine-learning-toolbox)

**Data Science in R (Advanced Track) -- Exchange Pool**

-   [Interactive Maps with leaflet in R (4h)](https://www.datacamp.com/courses/interactive-maps-with-leaflet-in-r)
-   [Interactive Data Visualization with plotly in R (4h)](https://app.datacamp.com/learn/courses/interactive-data-visualization-with-plotly-in-r)
-   [Multiple and Logistic Regression in R (4h)](https://www.datacamp.com/courses/multiple-and-logistic-regression)
-   [Supervised Learning in R: Regression (4h)](https://www.datacamp.com/courses/supervised-learning-in-r-regression)
-   [Unsupervised Learning in R (4h)](https://www.datacamp.com/courses/unsupervised-learning-in-r)
-   [Machine Learning in Tidyverse (5h)](https://www.datacamp.com/courses/machine-learning-in-the-tidyverse)
-   [Support Vector Machines in R (4h)](https://www.datacamp.com/courses/support-vector-machines-in-r)
-   [Introduction to Writing Functions in R (4h)](https://app.datacamp.com/learn/courses/introduction-to-writing-functions-in-r)
-   [Writing Efficient R Code (4h)](https://www.datacamp.com/courses/writing-efficient-r-code)
-   [Optimizing R Code with Rcpp (4h)](https://www.datacamp.com/courses/optimizing-r-code-with-rcpp)

:::

### Helpful Links

-   [RStudio Cheat Sheets](https://rstudio.cloud/learn/cheat-sheets)
-   [RMarkdown Explanation](https://rmarkdown.rstudio.com/lesson-1.html) (to document your analyses)
-   [StackOverflow](https://stackoverflow.com/) (forum for all kinds of coding questions)
-   [CrossValidated](https://stats.stackexchange.com/) (Statistics and Data Science forum)

## What's Python?

`Python` is a dynamic programming language.
You can execute the code in the interpreter, so you do not have to compile the code first.
This feature makes `Python` very easy and quick to use.
The excellent usability, easy readability, and simple structuring were and still are core ideas in developing this programming language.

You can use `Python` to program according to any paradigm, whereby structured and object-oriented programming is most straightforward due to the structure of the language.
Still, functional or aspect-oriented programming is also possible.
These options give users significant freedom to design projects the way they want and great space to write code that is difficult to understand and confusing.
For this reason, programmers developed specific standards based on the so-called `Python` Enhancement Proposals (PEP) over the decades.

### Anaconda and Jupyter

Before you can use `Python`, you must install it on the computer.
`Python` is already installed on Linux and Unix systems (such as macOS), but often it is an older version.
Since there are differences in the handling of `Python` version 2 -- which is no longer supported -- and version 3, we decided to work with version 3.6 or higher.

One of the easiest ways to get Python and most of the best-known programming libraries is to install Anaconda.
There are detailed explanations for installing all operating systems on the [website](https://docs.anaconda.com/anaconda/install/) of the provider.

With Anaconda installed, all you have to do is open the Anaconda Navigator, and you're ready to go.
There are two ways to get started: Spyder or Jupyter.
Spyder is the integrated development environment (IDE) for `Python` and offers all possibilities from syntax highlighting to debugging (links to tutorials below).

The other option is to use Jupyter or Jupyter notebooks.
It is an internet technology-based interface for executing commands.
The significant advantage of this is that you can quickly write shortcode pieces and try them out interactively without writing an entire executable program.
Now you can get started!

If you have not worked with Jupyter before, we recommend that you complete [this DataCamp course](https://app.datacamp.com/learn/projects/introduction-to-projects/guided/Python) first.
There you will get to know many tips and tricks that will make your workflow with Jupyter much easier.

To make your work and, above all, the collaboration more accessible, we are working with the [Google Colab](https://colab.research.google.com/notebooks/basic_features_overview.ipynb) platform that contains a Jupyter environment with the necessary libraries.
You can then import all the data required for the project with Google Drive.
We will introduce this environment during our first Coding Meetup.
Until then, focus on learning the "hard skills" of programming with your courses on DataCamp.
This topic brings us to your curriculum in the next section!

### Curriculum and DataCamp courses

The following list shows the required DataCamp courses for the Data Science with `Python` Track at TechAcademy.
As a beginner, please stick to the courses of the "beginner" program.
Ambitious beginners can, of course, take the advanced courses afterward.
However, it would be best if you worked through the courses in the order we listed them.

The same applies to the advanced courses.
Here, too, you should finish the specified courses in the given order.
Since it can, of course, happen that you have already mastered the topics of an advanced course, you can replace some courses.
If you are convinced that the course does not add value to you, feel free to replace it with one of the courses in the "Exchange Pool" (see list below).
However, you should not pursue an exchange course until you finish all chapters from the advanced course: "Intermediate Python."

To receive the certificate, both beginners and advanced learners must complete at least two-thirds of the curriculum (6/9 courses).
For the beginners, this means until -- and including -- the course "[Joining Data with pandas (4h)](https://www.datacamp.com/courses/joining-data-with-pandas)" and for the advanced until --and including -- "[Introduction to Linear Modeling in Python (4h)](https://www.datacamp.com/courses/introduction-to-linear-modeling-in-python)." In addition, you should complete at least *two-thirds* of the project tasks.
After completing the curriculum and the project's (minimal) requirements, you will receive your TechAcademy certificate!

::: {.tipsp .python data-latex="p"}
**Python Fundamentals (Beginner Track)**

1.  [Introduction to Data Science in Python (4h)](https://app.datacamp.com/learn/courses/intro-to-python-for-data-science)
2.  [Intermediate Python (4h)](https://app.datacamp.com/learn/courses/intermediate-python)
3.  [Python for Data Science Toolbox (Part 1) (3h)](https://app.datacamp.com/learn/courses/python-data-science-toolbox-part-1)
4.  [Introduction to Data Visualization with Matplotlib (4h)](https://app.datacamp.com/learn/courses/introduction-to-data-visualization-with-matplotlib)
5.  [Data Manipulation with pandas (4h)](https://app.datacamp.com/learn/courses/data-manipulation-with-pandas)
6.  [Joining Data with pandas (4h)](https://app.datacamp.com/learn/courses/joining-data-with-pandas)
7.  [Exploratory Data Analysis in Python (4h)](https://app.datacamp.com/learn/courses/exploratory-data-analysis-in-python)
8.  [Working with Dates and Times in Python (4h)](https://app.datacamp.com/learn/courses/working-with-dates-and-times-in-python)
9.  [Introduction to Importing Data in Python (3h)](https://app.datacamp.com/learn/courses/introduction-to-importing-data-in-python)

**Data Science with Python (Advanced Track)**

1.  [Intermediate Python (4h)](https://app.datacamp.com/learn/courses/intermediate-python)
2.  [Python Data Science Toolbox (Part 1) (3h)](https://app.datacamp.com/learn/courses/python-data-science-toolbox-part-1)
3.  [Python Data Science Toolbox (Part 2) (4h)](https://app.datacamp.com/learn/courses/python-data-science-toolbox-part-2)
4.  [Cleaning Data in Python (4h)](https://app.datacamp.com/learn/courses/cleaning-data-in-python)
5.  [Exploratory Data Analysis in Phyton (4h)](https://app.datacamp.com/learn/courses/exploratory-data-analysis-in-python)
6.  [Introduction to Linear Modeling in Python (4h)](https://www.datacamp.com/courses/introduction-to-linear-modeling-in-python)
7.  [Statistical Thinking in Python (Part 1) (3h)](https://app.datacamp.com/learn/courses/statistical-thinking-in-python-part-1)
8.  [Time Series Analysis in Python (4h)](https://app.datacamp.com/learn/courses/time-series-analysis-in-python)
9.  [Machine Learning for Time Series Data in Python (4h)](https://app.datacamp.com/learn/courses/machine-learning-for-time-series-data-in-python)

**Data Science with Python (Advanced Track) - Exchange Pool**

-   [Interactive Data Visualization with Bokeh (4h)](https://app.datacamp.com/learn/courses/interactive-data-visualization-with-bokeh)
-   [Data Visualization with Seaborn (4h)](https://app.datacamp.com/learn/courses/introduction-to-data-visualization-with-seaborn)
-   [Supervised Learning with scikit-learn (4h)](https://app.datacamp.com/learn/courses/supervised-learning-with-scikit-learn)
-   [Linear Classifiers in Python (4h)](https://app.datacamp.com/learn/courses/linear-classifiers-in-python)
-   [Unsupervised Learning in Python (4h)](https://app.datacamp.com/learn/courses/unsupervised-learning-in-python)
-   [Introduction to Deep Learning in Python (4h)](https://app.datacamp.com/learn/courses/introduction-to-deep-learning-in-python)
-   [ARIMA Models in Python (4h)](https://app.datacamp.com/learn/courses/arima-models-in-python)
-   [Web Scraping in Python (4h)](https://app.datacamp.com/learn/courses/web-scraping-with-python)
-   [Writing Efficient Python Code (4h)](https://app.datacamp.com/learn/courses/writing-efficient-python-code)
-   [Writing Efficient Code with pandas (4h)](https://app.datacamp.com/learn/courses/writing-efficient-code-with-pandas)
:::

[//]: # https://app.datacamp.com/learn/courses/statistical-thinking-in-python-part-2
[//]: # https://app.datacamp.com/learn/courses/machine-learning-with-tree-based-models-in-python

### Helpful Links

Official Tutorials/Documentation:

-   <https://docs.python.org/3/tutorial/index.html>
-   <https://jupyter.org/documentation>

Further Explanations:

-   <https://pythonprogramming.net/>
-   <https://automatetheboringstuff.com/>
-   <https://www.reddit.com/r/learnpython>
-   <https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook>

## Your Data Science Project

Participant's Section:

-   <https://www.tech-academy.io/teilnehmerbereich>

### Prelude 
Now that you have learned the theoretical foundation of Data Science in the DataCamp courses, you can put your skills into practice. We have put together a project for you based on real data sets. You can read about the details of this project in the following chapters of this project guide.
If you still feel a little unsure about how to start off, there will be a **Coding Introduction**  on **May 4, 2022**, where we will give you a general sense on how to start off with `Python` or `R`. 
Of course, we will also describe the project. We will discuss everything you need to know during the first **Coding Meetup**, which will take place on **May 18, 2022**. After that, your work on the project will officially begin. You can find the exact project tasks together with further explanations and hints in the following chapters.
To receive your TechAcademy certificate, you must solve at least two-thirds of the “Exploratory Data Analysis” section of your Data Science project if you are a beginner. We added the "Seasonality and Geographic Differences – Application of Statistical Methods" section for our advanced participants.
In addition, you should complete two-thirds (6/9 courses) of the respective curriculum on DataCamp, as mentioned. You can find more detailed information about the curriculum in the “Curriculum” section of the different programming languages above.

### Coding Meetups
To give you a little overview on the dates of our Meetups, you can find all the dates in one go here!
-   **27.04.2022**, Kick-Off Event
-   **04.05.2022**, Coding Introduction
-   **18.05.2022**, Coding MeetUp 1 
-   **01.06.2022**, Coding MeetUp 2 
-   **15.06.2022**, Coding MeetUp 3
-   **29.06.2022**, Coding MeetUp 4

### Deadline 
For both your DataCamp courses and the project files hand-in the deadline is **03.07.2022, 23:59** 

