---
editor_options: 
  markdown: 
    wrap: sentence
---

\newpage

# Exercise Checklist

This checklist should help you keep track of your exercises. Remember that you have to hand in satisfactory solutions to at least *two-thirds* of the exercises. If you're part of the beginner track, this refers to two-thirds of section 4 (EDA) only. If you're part of the advanced track, you have to hand in at least two-thirds of  section 4 and 5. Hence, you'll need more than 66% in each of the two sections for a certificate.

**Part 1: Exploratory Data Analysis (Beginner + Advanced Tracks)**

&check;  You completed at least 6 courses on Datacamp.
&check;  You completed at least two-third of section 4.
&check;  You checked that you included everything you coded in the right order and added explanatory comments.
&check;  You have all your output in the desired format.
&check;  You compared your output with your group. 
&check;  Finally, you can hand in your final work in time *(Remeber: Each team member has to hand in their final work individually, in any case it can be the same within the group)*

**Part 2: Seasonality and Geographic Differences – Application of Statistical Methods (motivated Beginner + Advanced Tracks)**

&check;  Everything of the above
&check;  In addition to you also completed at least two-third of section 5. 
